i#6949: Enable core-sharded by default for simulators (#7042)
Adds a new interface trace_analysis_tool::preferred_shard_type() to the
drmemtrace framework to allow tools to request core-sharded operation.

The cache simulator, TLB simulator, and schedule_stats tools override
the new interface to request core-sharded mode.

In the launcher, if all tools prefer core-sharded, and the user did not
specify sharding (via -[no_]core_{sharded,serial} or -cpu_scheduling),
then core-sharded (or core-serial) mode is enabled, with a -verbose 1+
message.
```
  $ bin64/drrun -stderr_mask 0 -t drcachesim -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir/ -verbose 1 -tool schedule_stats:cache_simulator
  Enabling -core_serial as all tools prefer it
  <...>
  Schedule stats tool results:
  Total counts:
             4 cores
             8 threads: 1257600, 1257602, 1257599, 1257603, 1257598, 1257604, 1257596, 1257601
  <...>
  Core #0 schedule: AEA_A_
  <...>
  Cache simulation results:
  Core #0 (traced CPU(s): #0)
    L1I0 (size=32768, assoc=8, block=64, LRU) stats:
      Hits:                          123,659
  <...>
```

If sharding is not specified and tools do not agree on a preferred type
(with the default being preferring thread-sharded, if a tool does not
override the new method), an error is raised to avoid confusion:
```
  $ bin64/drrun -t drcachesim -indir ../src/clients/drcachesim/tests/drmemtrace.threadsig.x64.tracedir -tool cache_simulator:basic_counts
  ERROR: failed to initialize analyzer: Selected tools differ in preferred sharding: please re-run with -[no_]core_sharded or -[no_]core_serial
```

Unfortunately, it is not easy to detect core-sharded-on-disk traces in
the launcher, so the user must now pass `-no_core_sharded` when using
such traces with core-sharded-preferring tools to avoid the trace being
re-scheduled yet again. Documentation for this is added and it is turned
into a fatal error since this re-scheduling there is almost certainly
user error.

Reduces the scheduler queue diagnostics by 5x as they seem too frequent
in short runs of the simulator with the new defaults, which new users
are going to see.

Updates the documentation proper and the options documentation to
describe the new defaults.

Updates numerous drcachesim test output templates.

Keeps a couple of simulator tests using thread-sharded by passing
-no_core_serial.

Fixes #6949