i#4915 nofetch: Improve analyzer scheduler error reporting (#8168)
Includes the scheduler error string in errors returned to the analyzer.

Changes the analyzer's scheduler_ field to become a unique_ptr, to
better support code sharing with subclasses, including error
reporting.

Adds a per-stream error string to avoid races accessing the
overall scheduler object's string for non-initialization errors.

Adds an exit path in the scheduler's rebalance_queues() if there are no
live outputs. Withtout this, an error in one output thread can cause
another doing a rebalance to hit a floating point crash, which was hit
and confirmed fixed.

Tested on forthcoming #4915 kernel template versioning changes which
return an error if the right version is missing. Without this change,
the error showed up as a vague "Failed to read from trace". With this
change it says:
```
ERROR: failed to run analyzer: Failed on allasm_x86_64_ver5.trace.zip: \
Failed to find syscall sequence for version 5 and number 1
```

Issue: #4915