i#7344: Do not skip vera tests when format checks are disabled. (#7388)
#7361 disables vera checks when DISABLE_FORMAT_CHECKS is present in
commit messages.

It led to #7330 breaking subsequent tests due to failed style checks. 
Files should be added to make/style_checks/exclude to skip vera tests
until formats are fixed. Revert the changes to skip vera checks when
DISABLE_FORMAT_CHECKS is set.

Also change suite/runsuite.cmake so that tabs check allow tabs to be
removed from existing files, i.e. files merged with
DISABLE_FORMAT_CHECKS set.

Tests:
Make a change with a tab and ensure the check still catches it:
```
$ ./suite/runsuite_wrapper.pl automated_ci 64_only require_format 
Forking child for stdout tee
Parent tee-ing child stdout...
Running ctest --output-on-failure -VV -S "/usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake,automated_ci;64_only;require_format"
* Extra verbosity turned on
Reading Script: /usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake,automated_ci;64_only;require_format
ldd --version: ldd (Debian GLIBC 2.40-6+gl0) 2.40
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

-- Found Python3: /usr/bin/python3 (found version "3.12.8") found components: Interpreter
clang-format check passed
-- test adding tab
CMake Error at /usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake:311 (message):
  ERROR: diff contains tabs:

  +	message(STATUS "test adding tab")


Finished running ctest --output-on-failure -VV -S "/usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake,automated_ci;64_only;require_format"

====> FAILURE in runsuite script itself <====
CMake Error at /usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake:311 (message):

====> FAILURE in diff pre-commit checks <====
  ERROR: diff contains tabs:

  +	message(STATUS "test adding tab")


Finished running ctest --output-on-failure -VV -S "/usr/local/google/home/kyluk/format-checks/dynamorio/suite/runsuite.cmake,automated_ci;64_only;require_format"
```

Issue: #7344