i#5036 AArch64 scatter/gather: Fix GCC 13.2 compiler error (#7035)
Fixes the compiler error seen on GCC 13.2:

ext/drx/scatter_gather_aarch64.c:1238:37: error:
array subscript 2 is above array bounds of 'sg_slot_t[2]' {aka 'struct
_sg_slot_t[2]'}
    [-Werror=array-bounds=]
1238 | DR_ASSERT(slot_state->pred_slots[slot].kind == SLOT_KIND_UNUSED);

In practice the code will never make an out of bounds access because the
for loop above will always terminate by breaking so `slot` is always `<
NUM_PRED_SLOTS`.

Issue: #5036